### ISSUE TITLE
 Plugin crashes when artifacts that do not contain the expected payload.

### ISSUE THREAD

**Issue by arjunspanicker** [BESTSELLER/backstage-plugin-harbor#183]
The example we had was an incomplete aqua scanned artifact that return json, but it didn't contain the severity field, causing the plugin to crash

**Comment by johanhammar** [comment]
I wonder if it is the same as I reported https://github.com/BESTSELLER/backstage-plugin-harbor-backend/issues/59

As a temporary solution I changed the vulnkey but a more stable solution is needed

-    const vulnKey = "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0";
+    const vulnKey = "application/vnd.security.vulnerability.report; version=1.1";

**Comment by JasonC17** [comment]
Is there any progress on this ticket?  As per Arjun's comment, 

The harbor plugin crashes after
- the api retrieves the json response from harbor and it doesn't contain the severity field.  
 
This scenario occurs because:
- we are running a large volume of scans using aquasec and on occasion those checks fail, 
- that results in an incomplete scan, 
- resulting in the severity for any vulnerabilities not being populated.

@johanhammar -  i don't believe this is related.  We definitely get a response, but it contains no vulnerability information.  i.e. severity.

**Comment by Gaardsholt** [comment]
As we are no longer using Harbor, we will now archive this repo.
We would love to donate the project to someone else, so if anyone wanna take over the project they can contact us on EngineeringServices@bestseller.com
